//
//  UserMangementException.swift
//  Quickride
//
//  Created by KNM Rao on 26/11/16.
//  Copyright © 2014-2020. Quick Ride (www.quickride.in). All rights reserved.
//  iDisha Info Labs Pvt Ltd. proprietary.
//

import Foundation
class UserMangementException {
  
  static let USER_MGMT_ERROR_STARTER = 1000
  static let USER_ALREADY_EXIST : Int = 1002
  static let USER_CREATION_FAILED = 1003
  static let USER_NOT_REGISTERED = 1004
  static let USER_INFO_NOT_ACCESSIBLE = 1005
  static let USER_CREDENTILS_NOT_CORRECT = 1006
  static let USER_NOT_ACTIVATED = 1007
  static let USER_EXISTED_PASSWORD_NOT_CORRECT = 1011
  static let USER_VERIFYING_FAILED = 1104
  static let PROBLEM_WITH_GETTING_DATA = 1106
  static let GET_USER_STATUS_FAILED = 1109
  static let GETTING_USER_FAVOURITE_LOCATIONS_FAILED = 1111
  static let CREATING_USER_FAVOURITE_LOcATIONS_FAILED = 1112
  static let DELETE_FAVOURITE_LOCATIONS_FAILED = 1113
  static let CREATING_USER_SOCIAL_NW_DETAILS_FAILED = 1115
  static let GETTING_RESOURCE_FAILED = 1117
  static let UPDATING_PASSWORD_FAILED = 1118
  static let USER_PROFILE_CREATION_FAILED = 1119
  static let GETTING_USER_PROFILE_FAILED = 1120
  static let GETTING_USER_FAILED = 1121
  static let USER_PROFILE_UPDATION_FAILED = 1122
  static let GETTING_USER_IMAGE_ID_FAILED = 1123
  static let SEETTING_USER_IMAGE_ID_FAILED = 1124
  static let CLIENTUNIQUEDEVICEID_CONSTRAINT_FAILED = 1125
  static let GETTING_ATTRIBUTES_FAILED = 1126
  static let USER_OFFICE_EMAIL_STATUS_UPDATING_FAILED = 1127
  static let GET_USER_GENDER_FAILED = 1128
  static let USER_DEVICE_ID_UPDATION_FAILED = 1133
  static let GETTING_VEHICLE_FAILED = 1704
  static let CREATE_VEHICLE_FOR_USER_FAILED = 1706
  static let GETTING_VEHICLE_IMAGE_ID_FAILED = 1707
  static let SETTING_VEHICLE_IMAGE_ID_FAILED = 1708
  static let USER_RATING_GETTING_FAILED = 1803
  static let SAVE_FEEDBACK_FAILED = 1129
  static let SAVE_IMAGE_FAILED = 1130
  static let UPDATE_IMAGE_FAILED = 1131
  static let GETTING_IMAGE_FAILED = 1132
  static let USER_NO_EMERGENCY_CONTACT_ERROR = 1134
  static let CHECKING_REFERRAL_CODE_EXISTENCE_FAILED = 1135
  static let UPDATING_NO_OF_RIDES_FAILED = 1136
  static let GETTING_NO_OF_RIDES_FAILED = 1137
  static let PASSWORD_CANNOT_BE_EMPTY = 1138
  static let SAVING_IMAGE_TO_S3_FAILED = 1139
  static let USER_REG_BUT_ACTIVATION_CODE_NOT_SENT = 1140
  static let SYSTEM_FEEDBACK_SUBMISSION_FAILED = 1141
  static let USER_CONTACTS_RETRIEVAL_FAILED = 1142
  static let USER_ROUTE_GROUP_EXISTED_ALREADY_ERROR = 1143
  static let USER_ROUTE_GROUP_CREATE_FAILED_ERROR = 1144
  static let USER_ROUTE_GROUP_JOIN_FAILED_ERROR = 1145
  static let USER_ROUTE_GROUP_UNJOIN_FAILED_ERROR = 1146
  static let USER_ROUTE_GROUP_UPDATION_FAILED_ERROR = 1147
  static let USER_ALREADY_JOINED_TO_GROUP_ERROR = 1148
  static let USER_MGMT_INVALID_DATA_ERROR = 1149
  static let RESOURCE_CREATION_FAILED = 1150
  static let EMAIL_NOT_MATCHE_WITH_COMPANY_NAME_ERROR = 1151
  static let USER_NOTIFICATION_SETTINGS_CREATION_FAILED = 1152
  static let USER_NOTIFICATION_SETTINGS_UPDATION_FAILED = 1153
  static let USER_ACCOUNT_SUSPENDED_ERROR = 1154
  static let COMPANY_NAME_NOT_CONFIGURRED_ERROR = 1155
  static let EMAIL_ALREADY_EXISTS_ERROR = 1156
  static let USER_NOT_SET_COMPANY_NAME_OFFICIAL_EMAIL_PROPERLY_ERROR = 1157
  static let DATA_BASE_ACCESS_ERROR = 999
  static let REFERRAL_ERROR_STARTER = 5000
  static let REFERRAL_CODE_CREATION_FAILED = 5601
  static let GETTING_REFERRAL_CODE_FAILED = 5602
  static let REFERRAL_CODE_NOT_EXISTS = 5604
  static let REFERRAL_CODE_INVALID = 5605
  static let REFERRAL_CODE_NOT_APPLICABLE_FOR_THE_GIVEN_DATE_ERROR = 5606
  static let REFERRAL_CODE_ALREADY_USED = 5607
  static let FREE_RIDE_ID_UPDATING_FAILED_ERROR = 6900
  static let FREE_RIDE_MAPPING_SAVE_FAILED_ERROR = 6901
  static let SERIVCE_INTERNAL_ERROR = 9202
  static let PAYTM_WALLET_LOW_BALANCE = 3818
  static let QR_USER_ACCOUNT_SUSPENDED_ERROR = 1165
}
